development:
  adapter: mysql2 
  database: fcms
  username: fcms 
  password: pass
  host: localhost

test: &test
  adapter: mysql2 
  database: fcms
  username: fcms 
  password: pass
  host: localhost

production:
  adapter: mysql2 
  database: fcms_production
  username: fcms_production 
  password: q8pResWUTh*& 
  host: localhost

cucumber:
  <<: *test
