development:
  adapter: postgresql
  database: fcms
  username: root
  password: pass
  host: localhost

test: &test
  adapter: postgresql
  database: fcms
  username: root
  password: pass
  host: localhost

production:
  adapter: postgresql
  database: fcms
  username: root
  password: pass
  host: localhost

cucumber:
  <<: *test